# Generated by Django 4.0 on 2021-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0002_alter_car_slug_alter_manufacturer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
