# Generated by Django 4.0 on 2021-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0003_alter_car_slug_alter_manufacturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='main',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
