# Generated by Django 4.0 on 2022-01-01 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0004_car_main_manufacturer_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, unique=True),
        ),
    ]
