# Generated by Django 4.0.1 on 2022-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0005_car_description_alter_car_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
