# Generated by Django 4.0.1 on 2022-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_description_alter_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
